language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
install:
  - composer self-update
  - composer install
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
before_script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then echo 'phpenv config-add travis.ini; fi
script: php ./vendor/bin/codecept run unit --coverage